// One-off (re-runnable) generator that injects SEO + Open Graph meta tags into
// every page's <head>. Model pages are driven by src/data/models.js (looked up
// by the page's data-model slug); the four main pages come from MAIN_PAGES below.
//
// The injected block is wrapped in <!-- meta:auto --> markers, so running this
// again simply replaces the previous block (idempotent). Run with:
//   node scripts/inject-meta.mjs
import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { globSync } from 'glob';
import { MODELS } from '../src/data/models.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'src');
const SITE = 'https://origami-3d-website.pages.dev';
const SITE_NAME = 'Origami Collection';

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// Build a one-line, ~150-char description for a model from its descriptor.
function modelDescription(m) {
  const family = m.type || 'modular origami';
  const shape = m.shape ? m.shape.toLowerCase() : null;
  let body;
  if (shape && m.pieces) {
    body = `a modular origami ${shape} folded from ${m.pieces} ${family} units`;
  } else if (shape) {
    body = `a modular origami ${shape} hand-folded from ${family} units`;
  } else {
    body = `a modular origami model hand-folded by hand`;
  }
  return `${m.name}: ${body}, recreated as an interactive 3D model you can rotate and recolor.`;
}

// Assemble the marker-wrapped <head> block. ogTitle defaults to the bare title.
function metaBlock({ title, ogTitle, description, url, image }) {
  const lines = [
    '<!-- meta:auto:start (generated by scripts/inject-meta.mjs) -->',
    `<title>${esc(title)}</title>`,
    `<meta name="description" content="${esc(description)}">`,
    `<meta property="og:type" content="website">`,
    `<meta property="og:site_name" content="${esc(SITE_NAME)}">`,
    `<meta property="og:title" content="${esc(ogTitle ?? title)}">`,
    `<meta property="og:description" content="${esc(description)}">`,
    `<meta property="og:url" content="${esc(url)}">`,
    `<meta property="og:image" content="${esc(image)}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    '<!-- meta:auto:end -->',
  ];
  return lines.join('\n  ');
}

// Strip any prior auto-block and the original/loose <title>, then insert fresh
// meta as the last thing inside <head>.
function inject(file, block) {
  let html = readFileSync(file, 'utf8');
  html = html.replace(/[ \t]*<!-- meta:auto:start[\s\S]*?<!-- meta:auto:end -->\n?/g, '');
  html = html.replace(/[ \t]*<title>[\s\S]*?<\/title>\n?/i, '');
  if (!/<\/head>/i.test(html)) {
    console.warn(`! no </head> in ${file}, skipped`);
    return false;
  }
  html = html.replace(/<\/head>/i, `  ${block}\n</head>`);
  writeFileSync(file, html);
  return true;
}

// --- The four hand-authored main pages ---------------------------------------
const HERO_IMG = `${SITE}/Gallery_PNG/Sonobe_144pcs.png`;
const MAIN_PAGES = [
  {
    file: 'index.html',
    title: 'Origami Collection · Modular Origami in 3D',
    ogTitle: 'Origami Collection',
    description: 'A digital archive of modular origami: dozens of models hand-folded from paper and rebuilt as interactive 3D pieces you can rotate and recolor in the browser.',
    url: `${SITE}/`,
    image: HERO_IMG,
  },
  {
    file: 'pages/models/index.html',
    title: 'Models · Origami Collection',
    ogTitle: 'Models',
    description: 'Browse the full catalog of modular origami models, from a 3-piece tetrahedron to a 360-piece icosahedron, each viewable as an interactive 3D piece.',
    url: `${SITE}/pages/models/`,
    image: `${SITE}/Models_PNG/Sonobe_Icosahedron.png`,
  },
  {
    file: 'pages/gallery/index.html',
    title: 'Gallery · Origami Collection',
    ogTitle: 'Gallery',
    description: 'Reference photos of the physical modular origami models, hand-folded from paper before being recreated in 3D.',
    url: `${SITE}/pages/gallery/`,
    image: HERO_IMG,
  },
  {
    file: 'pages/about/index.html',
    title: 'About · Origami Collection',
    ogTitle: 'About',
    description: 'About Origami Collection, a personal archive of modular origami hand-folded and digitized in 3D by a lifelong origami enthusiast.',
    url: `${SITE}/pages/about/`,
    image: HERO_IMG,
  },
];

let done = 0;
for (const p of MAIN_PAGES) {
  if (inject(resolve(src, p.file), metaBlock(p))) done++;
}

// --- Model viewer pages (data-driven) ----------------------------------------
const modelFiles = globSync('model_pages/**/index.html', { cwd: src });
let missing = 0;
for (const rel of modelFiles) {
  const file = resolve(src, rel);
  const slug = /data-model="([^"]+)"/.exec(readFileSync(file, 'utf8'))?.[1];
  const m = slug && MODELS[slug];
  if (!m) {
    console.warn(`! no model data for ${rel} (slug=${slug ?? 'none'})`);
    missing++;
    continue;
  }
  const block = metaBlock({
    title: `${m.name} · ${SITE_NAME}`,
    ogTitle: m.name,
    description: modelDescription(m),
    url: `${SITE}/model_pages/${slug}/`,
    image: `${SITE}${m.thumbnail}`,
  });
  if (inject(file, block)) done++;
}

console.log(`Injected meta into ${done} page(s). ${missing} model page(s) had no data.`);
