// Single source of truth for every model. Both the viewer pages (via page.js)
// and the Models catalog read from here. Keyed by slug, which matches the
// folder under /model_pages/ (e.g. "BowTie/BowTie_Hexahedron").
//
//   name      display name (page title bar + catalog card)
//   glb       model file under /GLB_Files/
//   thumbnail catalog image under /Models_PNG/
//   category  used for catalog filtering
//   palette   one color per part; length = number of colored parts (3 or 6)
//   piece     optional individual-piece image for the info panel
//   info      { label: value } fields shown in the expandable info panel

export const MODELS = {
  "48pcsSonobe": {
    name: "Sonobe - 48pcs",
    glb: "/GLB_Files/sonobemodule48pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_48pcs.png",
    category: "Compound",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 48,
      "Geometric Shape": "Compound of Hexahedron and Octahedron",
      "Number of Tetrahedron": 32,
      "Individual Piece": "Sonobe",
    },
  },

  "BowTie/BowTie_Hexahedron": {
    name: "Bow Tie Motif - Hexahedron",
    glb: "/GLB_Files/bowtiemodulehexahedron.glb",
    thumbnail: "/Models_PNG/BowTieMotif_Hexahedron.png",
    category: "BowTie",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/bowtiemotifpiece.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Hexahedron (Cube)",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Bow Tie Motif",
    },
  },

  "BowTie/BowTie_Icosahedron": {
    name: "Bow Tie Motif - Icosahedron",
    glb: "/GLB_Files/bowtiemoduleicosahedron.glb",
    thumbnail: "/Models_PNG/BowTieMotif_Icosahedron.png",
    category: "BowTie",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/bowtiemotifpiece.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Bow Tie Motif",
    },
  },

  "BowTie/BowTie_Octahedron": {
    name: "Bow Tie Motif - Octahedron",
    glb: "/GLB_Files/bowtiemoduleoctahedron.glb",
    thumbnail: "/Models_PNG/BowTieMotif_Octahedron.png",
    category: "BowTie",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/bowtiemotifpiece.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Bow Tie Motif",
    },
  },
  "TetraSonobe/TetraSonobe_Modif1": {
    name: "Sonobe - Tetrahedron Var. 1",
    glb: "/GLB_Files/sonobemoduletetrahedron_modif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron_Modif1.png",
    category: "TetraSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    info: {
      "Number of Pieces": 3,
      "Geometric Shape": "Double-sided Tetrahedron",
      "Number of Tetrahedron": 2,
      "Individual Piece": "Sonobe - Modification 1",
    },
  },
  "TetraSonobe/TetraSonobe_Modif2": {
    name: "Sonobe - Tetrahedron Var. 2",
    glb: "/GLB_Files/sonobemoduletetrahedron_modif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron_Modif2.png",
    category: "TetraSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    info: {
      "Number of Pieces": 3,
      "Geometric Shape": "Double-sided Tetrahedron",
      "Number of Tetrahedron": 2,
      "Individual Piece": "Sonobe - Modification 2",
    },
  },
  "TetraSonobe/TetraSonobe_Modif3": {
    name: "Sonobe - Tetrahedron Var. 3",
    glb: "/GLB_Files/sonobemoduletetrahedron_modif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron_Modif3.png",
    category: "TetraSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    info: {
      "Number of Pieces": 3,
      "Geometric Shape": "Double-sided Tetrahedron",
      "Number of Tetrahedron": 2,
      "Individual Piece": "Sonobe - Modification 3",
    },
  },
  "TetraSonobe": {
    name: "Sonobe - Tetrahedron",
    glb: "/GLB_Files/sonobemoduletetrahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron.png",
    category: "TetraSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 3,
      "Geometric Shape": "Double-sided Tetrahedron",
      "Number of Tetrahedron": 2,
      "Individual Piece": "Sonobe",
    },
  },
  "108pcsSonobe": {
    name: "Sonobe - 108pcs",
    glb: "/GLB_Files/sonobemoduleoctahedron_108pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_108pcs.png",
    category: "108pcsSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": "108pcs",
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "144pcsSonobe": {
    name: "Sonobe - 144pcs",
    glb: "/GLB_Files/sonobemodule144pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_144pcs.png",
    category: "144pcsSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": "144pcs",
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "HexaOctaSonobe/HexaOctaSonobe_Inverse": {
    name: "Sonobe - 36pcs Inverted",
    glb: "/GLB_Files/sonobemoduleoctahedron_36pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_HexaOctahedron_Inverse.png",
    category: "HexaOctaSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 36,
      "Geometric Shape": "Compound of Hexahedron and Octahedron",
      "Number of Tetrahedron": 24,
      "Individual Piece": "Sonobe",
    },
  },
  "HexaOctaSonobe": {
    name: "Sonobe - HexaOctaCompound",
    glb: "/GLB_Files/sonobemodulehexaoctahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_HexaOctahedron.png",
    category: "HexaOctaSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 36,
      "Geometric Shape": "Compound of Hexahedron and Octahedron",
      "Number of Tetrahedron": 24,
      "Individual Piece": "Sonobe",
    },
  },
  "HexaSonobe/HexaSonobe_Modif1": {
    name: "Sonobe - Hexahedron Var. 1",
    glb: "/GLB_Files/sonobemodulehexahedron_modif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron_Modif1.png",
    category: "HexaSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    info: {
      "Number of Pieces": 6,
      "Geometric Shape": "Hexahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Sonobe - Modification 1",
    },
  },
  "HexaSonobe/HexaSonobe_Modif2": {
    name: "Sonobe - Hexahedron Var. 2",
    glb: "/GLB_Files/sonobemodulehexahedron_modif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron_Modif2.png",
    category: "HexaSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    info: {
      "Number of Pieces": 6,
      "Geometric Shape": "Hexahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Sonobe - Modification 2",
    },
  },
  "HexaSonobe/HexaSonobe_Modif3": {
    name: "Sonobe - Hexahedron Var. 3",
    glb: "/GLB_Files/sonobemodulehexahedron_modif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron_Modif3.png",
    category: "HexaSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    info: {
      "Number of Pieces": 6,
      "Geometric Shape": "Hexahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Sonobe - Modification 3",
    },
  },
  "HexaSonobe": {
    name: "Sonobe - Hexahedron",
    glb: "/GLB_Files/sonobemodulehexahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron.png",
    category: "HexaSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 6,
      "Geometric Shape": "Hexahedron (Cube)",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Sonobe",
    },
  },
  "HexaSonobesize2": {
    name: "Sonobe - Hexahedron size 2",
    glb: "/GLB_Files/sonobemodulehexahedronsize2.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedronsize2.png",
    category: "HexaSonobesize2",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 24,
      "Geometric Shape": "Hexahedron (Cube)",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Sonobe",
    },
  },
  "HexaSonobesize3": {
    name: "Sonobe - Hexahedron size 3",
    glb: "/GLB_Files/sonobemodulehexahedronsize3.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedronsize3.png",
    category: "HexaSonobesize3",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 54,
      "Geometric Shape": "Hexahedron (Cube)",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_120pcs": {
    name: "Sonobe - 120pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_120pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_120pcs.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": "120pcs",
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_120pcs_Inverse": {
    name: "Sonobe - 120pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_120pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_120pcs_Inverse.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_270pcs": {
    name: "Sonobe - 270pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_270pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_270pcs.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": "270pcs",
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_270pcs_Inverse": {
    name: "Sonobe - 270pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_270pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_270pcs_Inverse.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 270,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 180,
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_360pcs": {
    name: "Sonobe - 360pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_360pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_360pcs.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": "360pcs",
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_360pcs_Inverse": {
    name: "Sonobe - 360pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_360pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_360pcs_Inverse.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 360,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_90pcs": {
    name: "Sonobe - 90pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_90pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_90pcs.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": "90pcs",
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": "",
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_90pcs_Inverse": {
    name: "Sonobe - 90pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_90pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_90pcs_Inverse.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_Inverse": {
    name: "Sonobe - 30pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedroninverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Inverse.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe",
    },
  },
  "IcoSonobe/IcoSonobe_Modif1": {
    name: "Sonobe - Icosahedron Var. 1",
    glb: "/GLB_Files/sonobemoduleicosahedronmodif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Modif1.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe - Modification 1",
    },
  },
  "IcoSonobe/IcoSonobe_Modif2": {
    name: "Sonobe - Icosahedron Var. 2",
    glb: "/GLB_Files/sonobemoduleicosahedronmodif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Modif2.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe - Modification 2",
    },
  },
  "IcoSonobe/IcoSonobe_Modif3": {
    name: "Sonobe - Icosahedron Var. 3",
    glb: "/GLB_Files/sonobemoduleicosahedronmodif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Modif3.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe - Modification 3",
    },
  },
  "IcoSonobe": {
    name: "Sonobe - Icosahedron",
    glb: "/GLB_Files/sonobemoduleicosahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron.png",
    category: "IcoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 30,
      "Geometric Shape": "Icosahedron",
      "Number of Tetrahedron": 20,
      "Individual Piece": "Sonobe",
    },
  },
  "OctoSonobe/OctaSonobe_Inverse": {
    name: "Sonobe - 12pcs Inverted",
    glb: "/GLB_Files/sonobemoduleoctahedron_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Inverse.png",
    category: "OctoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 8,
      "Individual Piece": "Sonobe",
    },
  },
  "OctoSonobe/OctaSonobe_Modif1": {
    name: "Sonobe - Octahedron Var. 1",
    glb: "/GLB_Files/sonobemoduleoctahedron_modif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Modif1.png",
    category: "OctoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 8,
      "Individual Piece": "Sonobe - Modification 1",
    },
  },
  "OctoSonobe/OctaSonobe_Modif2": {
    name: "Sonobe - Octahedron Var. 2",
    glb: "/GLB_Files/sonobemoduleoctahedron_modif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Modif2.png",
    category: "OctoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 8,
      "Individual Piece": "Sonobe - Modification 2",
    },
  },
  "OctoSonobe/OctaSonobe_Modif3": {
    name: "Sonobe - Octahedron Var. 3",
    glb: "/GLB_Files/sonobemoduleoctahedron_modif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Modif3.png",
    category: "OctoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 8,
      "Individual Piece": "Sonobe - Modification 3",
    },
  },
  "OctoSonobe": {
    name: "Sonobe - Octahedron",
    glb: "/GLB_Files/sonobemoduleoctahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron.png",
    category: "OctoSonobe",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 8,
      "Individual Piece": "Sonobe",
    },
  },
  "Poke/Poke_EnlargedOctahedron": {
    name: "Poke - Enlarged Octahedron",
    glb: "/GLB_Files/pokemoduleenlargedoctahedron.glb",
    thumbnail: "/Models_PNG/Poke_EnlargedOctahedron.png",
    category: "Poke",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#00ff83", "#aa22ff", "#0400ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    info: {
      "Number of Pieces": 6,
      "Geometric Shape": "Tetrahedron",
      "Number of Tetrahedron": 1,
      "Individual Piece": "Poke",
    },
  },
  "Poke/Poke_Hexahedron": {
    name: "Poke - Hexahedron",
    glb: "/GLB_Files/pokemodulehexahedron.glb",
    thumbnail: "/Models_PNG/Poke_Hexahedron.png",
    category: "Poke",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Hexahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Poke",
    },
  },
  "Poke/Poke_Octahedron": {
    name: "Poke - Octahedron",
    glb: "/GLB_Files/pokemoduleoctahedron.glb",
    thumbnail: "/Models_PNG/Poke_Octahedron.png",
    category: "Poke",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    info: {
      "Number of Pieces": 12,
      "Geometric Shape": "Octahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Poke",
    },
  },
  "Poke/Poke_Tetrahedron": {
    name: "Poke - Tetrahedron",
    glb: "/GLB_Files/pokemoduletetrahedron.glb",
    thumbnail: "/Models_PNG/Poke_Tetrahedron.png",
    category: "Poke",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    info: {
      "Number of Pieces": 6,
      "Geometric Shape": "Tetrahedron",
      "Number of Tetrahedron": 1,
      "Individual Piece": "Poke",
    },
  },
  "Pokev2/Pokev2_Octahedron": {
    name: "Poke v2 - Octahedron",
    glb: "/GLB_Files/pokev2moduleoctahedron.glb",
    thumbnail: "/Models_PNG/Pokev2_Octahedron.png",
    category: "Pokev2",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    info: {
      "Number of Pieces": 20,
      "Geometric Shape": "Tetrahedron",
      "Number of Tetrahedron": 4,
      "Individual Piece": "Poke v2",
    },
  },
  "Pokev2/Pokev2_Tetrahedron": {
    name: "Poke v2 - Tetrahedron",
    glb: "/GLB_Files/pokev2moduletetrahedron.glb",
    thumbnail: "/Models_PNG/Pokev2_Tetrahedron.png",
    category: "Pokev2",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    info: {
      "Number of Pieces": 10,
      "Geometric Shape": "Tetrahedron",
      "Number of Tetrahedron": 1,
      "Individual Piece": "Poke v2",
    },
  },
  "SonobePlane/Sonobe_Plane_15pcs": {
    name: "Sonobe - Plane 15pcs",
    glb: "/GLB_Files/sonobemoduleplane_15pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_Plane_15pcs.png",
    category: "SonobePlane",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 15,
      "Geometric Shape": "Plane",
      "Number of Tetrahedron": 10,
      "Individual Piece": "Sonobe",
    },
  },
  "SonobePlane/Sonobe_Plane_18pcs": {
    name: "Sonobe - Plane 18pcs",
    glb: "/GLB_Files/sonobemoduleplane_18pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_Plane_18pcs.png",
    category: "SonobePlane",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 18,
      "Geometric Shape": "Plane",
      "Number of Tetrahedron": 12,
      "Individual Piece": "Sonobe",
    },
  },
  "SonobePlane/Sonobe_Plane_72pcs": {
    name: "Sonobe - Plane 72pcs",
    glb: "/GLB_Files/sonobemoduleplane_72pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_Plane_72pcs.png",
    category: "SonobePlane",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    info: {
      "Number of Pieces": 72,
      "Geometric Shape": "Plane",
      "Number of Tetrahedron": 48,
      "Individual Piece": "Sonobe",
    },
  },
  "Uncategorized/DiagonalBox2": {
    name: "Diagonal Box 2",
    glb: "/GLB_Files/diagonalbox2.glb",
    thumbnail: "/Models_PNG/DiagonalBox2.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    info: {
    },
  },
  "Uncategorized/DiagonalBox": {
    name: "Diagonal Box",
    glb: "/GLB_Files/diagonalbox.glb",
    thumbnail: "/Models_PNG/DiagonalBox.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    info: {
    },
  },
  "Uncategorized/Holebox": {
    name: "Hole Box",
    glb: "/GLB_Files/holebox.glb",
    thumbnail: "/Models_PNG/HoleBox.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    info: {
    },
  },
  "Uncategorized/Icosahedron3": {
    name: "Icosahedron 3",
    glb: "/GLB_Files/icosahedron3.glb",
    thumbnail: "/Models_PNG/Icosahedron3.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    info: {
    },
  },
  "Uncategorized/Icosahedron4": {
    name: "Icosahedron 4",
    glb: "/GLB_Files/icosahedron4.glb",
    thumbnail: "/Models_PNG/Icosahedron4.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    info: {
    },
  },
  "Uncategorized/Icosahedron5": {
    name: "Icosahedron 5",
    glb: "/GLB_Files/icosahedron5.glb",
    thumbnail: "/Models_PNG/Icosahedron5.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    info: {
    },
  },
  "Uncategorized/Icosahedron6": {
    name: "Icosahedron 6",
    glb: "/GLB_Files/icosahedron6.glb",
    thumbnail: "/Models_PNG/Icosahedron6.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    info: {
    },
  },
  "Uncategorized/Octahedron3": {
    name: "Octahedron 3",
    glb: "/GLB_Files/octahedron3.glb",
    thumbnail: "/Models_PNG/Octahedron3.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    info: {
    },
  },
  "Fuse/Fuse_ExtrudedTetrahedron": {
    name: "Fuse - Enlarged Tetrahedron",
    glb: "/GLB_Files/fusemoduleenlargedtetrahedron.glb",
    thumbnail: "/Models_PNG/Fuse_EnlargedTetrahedron.png",
    category: "Fuse",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 10,
  },
  "Fuse/Fuse_Tetrahedron": {
    name: "Fuse - Tetrahedron",
    glb: "/GLB_Files/fusemoduletetrahedron.glb",
    thumbnail: "/Models_PNG/Fuse_Tetrahedron.png",
    category: "Fuse",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 10,
  },
  "Uncategorized/BoatDisk1": {
    name: "Boat Disk 1",
    glb: "/GLB_Files/boatdisk1.glb",
    thumbnail: "/Models_PNG/BoatDisk1.png",
    category: "Uncategorized",
    palette: ["#00ff83"],
    cameraZ: 10,
  },
  "Uncategorized/BoatDisk2": {
    name: "Boat Disk 2",
    glb: "/GLB_Files/boatdisk2.glb",
    thumbnail: "/Models_PNG/BoatDisk2.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ff7700", "#ffe600", "#00e0ff", "#ff2266"],
    cameraZ: 10,
  },
  "Uncategorized/BoxTriangle": {
    name: "Box Triangle",
    glb: "/GLB_Files/boxtriangle.glb",
    thumbnail: "/Models_PNG/BoxTriangle.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 15,
  },
  "Uncategorized/CrystalShape": {
    name: "Crystal Shape",
    glb: "/GLB_Files/crystalshape.glb",
    thumbnail: "/Models_PNG/CrystalShape.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 15,
  },
  "Uncategorized/CrystalShape2": {
    name: "Crystal Shape 2",
    glb: "/GLB_Files/crystalshape2.glb",
    thumbnail: "/Models_PNG/CrystalShape2.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 15,
  },
  "Uncategorized/Icosahedron2": {
    name: "Icosahedron 2",
    glb: "/GLB_Files/icosahedron2.glb",
    thumbnail: "/Models_PNG/Icosahedron2.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 10,
  },
  "Uncategorized/Icosahedron7": {
    name: "Icosahedron 7",
    glb: "/GLB_Files/icosahedron7.glb",
    thumbnail: "/Models_PNG/Icosahedron7.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ff7700"],
    cameraZ: 10,
  },
  "Uncategorized/Octahedron2": {
    name: "Octahedron 2",
    glb: "/GLB_Files/octahedron2.glb",
    thumbnail: "/Models_PNG/Octahedron2.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 10,
  },
  "Uncategorized/StarBox": {
    name: "Star Box",
    glb: "/GLB_Files/starbox.glb",
    thumbnail: "/Models_PNG/StarBox.png",
    category: "Uncategorized",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 10,
  },
};
