// Single source of truth for every model. Both the viewer pages (via page.js)
// and the Models catalog read from here. Keyed by slug, which matches the
// folder under /model_pages/ (e.g. "sonobe/octahedron/type-1/size-1").
//
// Required: name, glb, thumbnail, palette.
// Everything below is optional; the info panel renders only what is present.
//
//   name        display name (page title bar + catalog card)
//   glb         model file under /GLB_Files/
//   thumbnail   catalog image under /Models_PNG/
//   palette     one color per part; length = number of colored parts
//   piece       individual-piece image for the info panel
//   type        family used for catalog grouping
//   shape       geometric shape (also used for grouping)
//   pieces      number of modules
//   tetrahedra  number of constituent tetrahedra
//   quadrahedra number of constituent quadrahedra
//   pentahedra  number of constituent pentahedra
//   hexahedra   number of constituent hexahedra
//   variation   variation number (present => this is variation #N)
//   inverted    true when the model is the inverted coloring
//   cameraZ     camera distance override for the viewer

export const MODELS = {
  "sonobe/tetrahedron": {
    name: "Sonobe - Tetrahedron",
    glb: "/GLB_Files/sonobemoduletetrahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Tetrahedron",
    pieces: 3,
    tetrahedra: 2,
  },
  "sonobe/tetrahedron/variant-1": {
    variation: 1,
    name: "Sonobe - Tetrahedron Var. 1",
    glb: "/GLB_Files/sonobemoduletetrahedron_modif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron_Modif1.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    type: "Sonobe",
    shape: "Tetrahedron",
    pieces: 3,
    tetrahedra: 2,
  },
  "sonobe/tetrahedron/variant-2": {
    variation: 2,
    name: "Sonobe - Tetrahedron Var. 2",
    glb: "/GLB_Files/sonobemoduletetrahedron_modif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron_Modif2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    type: "Sonobe",
    shape: "Tetrahedron",
    pieces: 3,
    tetrahedra: 2,
  },
  "sonobe/tetrahedron/variant-3": {
    variation: 3,
    name: "Sonobe - Tetrahedron Var. 3",
    glb: "/GLB_Files/sonobemoduletetrahedron_modif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Tetrahedron_Modif3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    type: "Sonobe",
    shape: "Tetrahedron",
    pieces: 3,
    tetrahedra: 2,
  },
  "sonobe/hexahedron/size-1": {
    name: "Sonobe - Hexahedron",
    glb: "/GLB_Files/sonobemodulehexahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Hexahedron",
    pieces: 6,
    tetrahedra: 4,
  },
  "sonobe/hexahedron/size-1/variant-1": {
    variation: 1,
    name: "Sonobe - Hexahedron Var. 1",
    glb: "/GLB_Files/sonobemodulehexahedron_modif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron_Modif1.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    type: "Sonobe",
    shape: "Hexahedron",
    pieces: 6,
    tetrahedra: 4,
  },
  "sonobe/hexahedron/size-1/variant-2": {
    variation: 2,
    name: "Sonobe - Hexahedron Var. 2",
    glb: "/GLB_Files/sonobemodulehexahedron_modif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron_Modif2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    type: "Sonobe",
    shape: "Hexahedron",
    pieces: 6,
    tetrahedra: 4,
  },
  "sonobe/hexahedron/size-1/variant-3": {
    variation: 3,
    name: "Sonobe - Hexahedron Var. 3",
    glb: "/GLB_Files/sonobemodulehexahedron_modif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedron_Modif3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    type: "Sonobe",
    shape: "Hexahedron",
    pieces: 6,
    tetrahedra: 4,
  },
  "sonobe/octahedron/type-1/size-1": {
    name: "Sonobe - Octahedron",
    glb: "/GLB_Files/sonobemoduleoctahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 8,
    quadrahedra: 6,
  },
  "sonobe/octahedron/type-1/size-1/variant-1": {
    variation: 1,
    name: "Sonobe - Octahedron Var. 1",
    glb: "/GLB_Files/sonobemoduleoctahedron_modif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Modif1.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 8,
    quadrahedra: 6,
  },
  "sonobe/octahedron/type-1/size-1/variant-2": {
    variation: 2,
    name: "Sonobe - Octahedron Var. 2",
    glb: "/GLB_Files/sonobemoduleoctahedron_modif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Modif2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 8,
    quadrahedra: 6,
  },
  "sonobe/octahedron/type-1/size-1/variant-3": {
    variation: 3,
    name: "Sonobe - Octahedron Var. 3",
    glb: "/GLB_Files/sonobemoduleoctahedron_modif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Modif3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 8,
    quadrahedra: 6,
  },
  "sonobe/icosahedron/type-1/size-1": {
    name: "Sonobe - Icosahedron",
    glb: "/GLB_Files/sonobemoduleicosahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 30,
    tetrahedra: 20,
    pentahedra: 12,
  },
  "sonobe/icosahedron/type-1/size-1/variant-1": {
    variation: 1,
    name: "Sonobe - Icosahedron Var. 1",
    glb: "/GLB_Files/sonobemoduleicosahedronmodif1.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Modif1.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif1.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 30,
    tetrahedra: 20,
    pentahedra: 12,
  },
  "sonobe/icosahedron/type-1/size-1/variant-2": {
    variation: 2,
    name: "Sonobe - Icosahedron Var. 2",
    glb: "/GLB_Files/sonobemoduleicosahedronmodif2.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Modif2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif2.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 30,
    tetrahedra: 20,
    pentahedra: 12,
  },
  "sonobe/icosahedron/type-1/size-1/variant-3": {
    variation: 3,
    name: "Sonobe - Icosahedron Var. 3",
    glb: "/GLB_Files/sonobemoduleicosahedronmodif3.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Modif3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/sonobepiecemodif3.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 30,
    tetrahedra: 20,
    pentahedra: 12,
  },
  "sonobe/icosahedron/type-2/size-1": {
    name: "Sonobe - 90pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_90pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_90pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 90,
    tetrahedra: 60,
    pentahedra: 12,
    hexahedra: 20,
  },
  "sonobe/icosahedron/type-1/size-2": {
    name: "Sonobe - 120pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_120pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_120pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 120,
    tetrahedra: 80,
    pentahedra: 12,
    hexahedra: 30,
  },
  "sonobe/icosahedron/type-1/size-3": {
    name: "Sonobe - 270pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_270pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_270pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 270,
    tetrahedra: 180,
    pentahedra: 12,
    hexahedra: 80,
  },
  "sonobe/icosahedron/type-2/size-2": {
    name: "Sonobe - 360pcs",
    glb: "/GLB_Files/sonobemoduleicosahedron_360pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_360pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 360,
    tetrahedra: 240,
    pentahedra: 12,
    hexahedra: 110,
  },
  "sonobe/octahedron/type-2/size-1": {
    name: "Sonobe - HexaOctaCompound",
    glb: "/GLB_Files/sonobemodulehexaoctahedron.glb",
    thumbnail: "/Models_PNG/Sonobe_HexaOctahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 36,
    tetrahedra: 25,
    quadrahedra: 6,
    hexahedra: 8,
  },
  "sonobe/hexahedron/size-2": {
    name: "Sonobe - Hexahedron size 2",
    glb: "/GLB_Files/sonobemodulehexahedronsize2.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedronsize2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Hexahedron",
    pieces: 24,
    tetrahedra: 8,
    quadrahedra: 6,
  },
  "sonobe/hexahedron/size-3": {
    name: "Sonobe - Hexahedron size 3",
    glb: "/GLB_Files/sonobemodulehexahedronsize3.glb",
    thumbnail: "/Models_PNG/Sonobe_Hexahedronsize3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Hexahedron",
    pieces: 54,
    tetrahedra: 8,
    quadrahedra: 24,
  },
  "sonobe/octahedron/type-1/size-2": {
    name: "Sonobe - 48pcs",
    glb: "/GLB_Files/sonobemodule48pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_48pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 48,
    tetrahedra: 32,
    quadrahedra: 6,
    hexahedra: 12,
  },
  "sonobe/octahedron/type-1/size-3": {
    name: "Sonobe - 108pcs",
    glb: "/GLB_Files/sonobemoduleoctahedron_108pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_108pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 108,
    tetrahedra: 72,
    quadrahedra: 6,
    hexahedra: 32,
  },
  "sonobe/octahedron/type-2/size-2": {
    name: "Sonobe - 144pcs",
    glb: "/GLB_Files/sonobemodule144pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_144pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 144,
    tetrahedra: 96,
    quadrahedra: 6,
    hexahedra: 45,
  },
  "sonobe/plane/pentagon": {
    name: "Sonobe - Plane 15pcs",
    glb: "/GLB_Files/sonobemoduleplane_15pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_Plane_15pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Pentagon",
    pieces: 15,
    tetrahedra: 10,
    quadrahedra: 5,
    pentahedra: 2,
  },
  "sonobe/plane/hexagon/size-1": {
    name: "Sonobe - Plane 18pcs",
    glb: "/GLB_Files/sonobemoduleplane_18pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_Plane_18pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Hexagon",
    pieces: 18,
    tetrahedra: 12,
    quadrahedra: 6,
    hexahedra: 6,
  },
  "sonobe/plane/hexagon/size-2": {
    name: "Sonobe - Plane 72pcs",
    glb: "/GLB_Files/sonobemoduleplane_72pcs.glb",
    thumbnail: "/Models_PNG/Sonobe_Plane_72pcs.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Hexagon",
    pieces: 72,
    tetrahedra: 48,
    quadrahedra: 6,
    hexahedra: 20,
  },
  "sonobe/octahedron/type-1/size-1/inverted": {
    inverted: true,
    name: "Sonobe - 12pcs Inverted",
    glb: "/GLB_Files/sonobemoduleoctahedron_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Octahedron_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 8,
    quadrahedra: 6,
  },
  "sonobe/octahedron/type-2/size-1/inverted": {
    inverted: true,
    name: "Sonobe - 36pcs Inverted",
    glb: "/GLB_Files/sonobemoduleoctahedron_36pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_HexaOctahedron_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Octahedron",
    pieces: 36,
    tetrahedra: 25,
    quadrahedra: 6,
    hexahedra: 8,
  },
  "sonobe/icosahedron/type-1/size-1/inverted": {
    inverted: true,
    name: "Sonobe - 30pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedroninverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 30,
    tetrahedra: 20,
    pentahedra: 12,
  },
  "sonobe/icosahedron/type-2/size-1/inverted": {
    inverted: true,
    name: "Sonobe - 90pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_90pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_90pcs_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 90,
    tetrahedra: 60,
    pentahedra: 12,
    hexahedra: 20,
  },
  "sonobe/icosahedron/type-1/size-2/inverted": {
    inverted: true,
    name: "Sonobe - 120pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_120pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_120pcs_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 120,
    tetrahedra: 80,
    pentahedra: 12,
    hexahedra: 30,
  },
  "sonobe/icosahedron/type-1/size-3/inverted": {
    inverted: true,
    name: "Sonobe - 270pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_270pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_270pcs_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 270,
    tetrahedra: 180,
    pentahedra: 12,
    hexahedra: 80,
  },
  "sonobe/icosahedron/type-2/size-2/inverted": {
    inverted: true,
    name: "Sonobe - 360pcs Inverted",
    glb: "/GLB_Files/sonobemoduleicosahedron_360pcs_inverse.glb",
    thumbnail: "/Models_PNG/Sonobe_Icosahedron_360pcs_Inverse.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/sonobepiece.png",
    type: "Sonobe",
    shape: "Icosahedron",
    pieces: 360,
    tetrahedra: 240,
    pentahedra: 12,
    hexahedra: 110,
  },
  "bow-tie/hexahedron": {
    name: "Bow Tie Motif - Hexahedron",
    glb: "/GLB_Files/bowtiemodulehexahedron.glb",
    thumbnail: "/Models_PNG/BowTieMotif_Hexahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/bowtiemotifpiece.png",
    type: "Bow Tie Motif",
    shape: "Hexahedron",
    pieces: 12,
    tetrahedra: 4,
  },
  "bow-tie/octahedron": {
    name: "Bow Tie Motif - Octahedron",
    glb: "/GLB_Files/bowtiemoduleoctahedron.glb",
    thumbnail: "/Models_PNG/BowTieMotif_Octahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/bowtiemotifpiece.png",
    type: "Bow Tie Motif",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 4,
  },
  "bow-tie/icosahedron": {
    name: "Bow Tie Motif - Icosahedron",
    glb: "/GLB_Files/bowtiemoduleicosahedron.glb",
    thumbnail: "/Models_PNG/BowTieMotif_Icosahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    piece: "/Individual_Pieces/bowtiemotifpiece.png",
    type: "Bow Tie Motif",
    shape: "Icosahedron",
    pieces: 30,
    tetrahedra: 20,
  },
  "poke/tetrahedron": {
    name: "Poke - Tetrahedron",
    glb: "/GLB_Files/pokemoduletetrahedron.glb",
    thumbnail: "/Models_PNG/Poke_Tetrahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    type: "Poke",
    shape: "Tetrahedron",
    pieces: 6,
    tetrahedra: 1,
  },
  "poke/hexahedron": {
    name: "Poke - Hexahedron",
    glb: "/GLB_Files/pokemodulehexahedron.glb",
    thumbnail: "/Models_PNG/Poke_Hexahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    type: "Poke",
    shape: "Hexahedron",
    pieces: 12,
    tetrahedra: 4,
  },
  "poke/octahedron": {
    name: "Poke - Octahedron",
    glb: "/GLB_Files/pokemoduleoctahedron.glb",
    thumbnail: "/Models_PNG/Poke_Octahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    type: "Poke",
    shape: "Octahedron",
    pieces: 12,
    tetrahedra: 4,
  },
  "poke/enlarged-octahedron": {
    name: "Poke - Enlarged Octahedron",
    glb: "/GLB_Files/pokemoduleenlargedoctahedron.glb",
    thumbnail: "/Models_PNG/Poke_EnlargedOctahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#00ff83", "#aa22ff", "#0400ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    type: "Poke",
    shape: "Enlarged Octahedron",
    pieces: 6,
    tetrahedra: 1,
  },
  "poke-v2/tetrahedron": {
    name: "Poke v2 - Tetrahedron",
    glb: "/GLB_Files/pokev2moduletetrahedron.glb",
    thumbnail: "/Models_PNG/Pokev2_Tetrahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    type: "Poke",
    shape: "Tetrahedron",
    pieces: 10,
    tetrahedra: 1,
  },
  "poke-v2/octahedron": {
    name: "Poke v2 - Octahedron",
    glb: "/GLB_Files/pokev2moduleoctahedron.glb",
    thumbnail: "/Models_PNG/Pokev2_Octahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    piece: "/Individual_Pieces/pokepiece.png",
    type: "Poke",
    shape: "Octahedron",
    pieces: 20,
    tetrahedra: 4,
  },
  "fuse/tetrahedron": {
    name: "Fuse - Tetrahedron",
    glb: "/GLB_Files/fusemoduletetrahedron.glb",
    thumbnail: "/Models_PNG/Fuse_Tetrahedron.png",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 10,
    type: "Fuse",
  },
  "fuse/enlarged-tetrahedron": {
    name: "Fuse - Enlarged Tetrahedron",
    glb: "/GLB_Files/fusemoduleenlargedtetrahedron.glb",
    thumbnail: "/Models_PNG/Fuse_EnlargedTetrahedron.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 10,
    type: "Fuse",
  },
  "misc/box-triangle": {
    name: "Box Triangle",
    glb: "/GLB_Files/boxtriangle.glb",
    thumbnail: "/Models_PNG/BoxTriangle.png",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 15,
    type: "Misc",
  },
  "misc/octahedron-2": {
    name: "Octahedron 2",
    glb: "/GLB_Files/octahedron2.glb",
    thumbnail: "/Models_PNG/Octahedron2.png",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 10,
    type: "Misc",
  },
  "misc/octahedron-3": {
    name: "Octahedron 3",
    glb: "/GLB_Files/octahedron3.glb",
    thumbnail: "/Models_PNG/Octahedron3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    type: "Misc",
  },
  "misc/icosahedron-2": {
    name: "Icosahedron 2",
    glb: "/GLB_Files/icosahedron2.glb",
    thumbnail: "/Models_PNG/Icosahedron2.png",
    palette: ["#00ff83", "#0400ff"],
    cameraZ: 10,
    type: "Misc",
  },
  "misc/icosahedron-3": {
    name: "Icosahedron 3",
    glb: "/GLB_Files/icosahedron3.glb",
    thumbnail: "/Models_PNG/Icosahedron3.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    type: "Misc",
  },
  "misc/icosahedron-4": {
    name: "Icosahedron 4",
    glb: "/GLB_Files/icosahedron4.glb",
    thumbnail: "/Models_PNG/Icosahedron4.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    type: "Misc",
  },
  "misc/icosahedron-5": {
    name: "Icosahedron 5",
    glb: "/GLB_Files/icosahedron5.glb",
    thumbnail: "/Models_PNG/Icosahedron5.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    type: "Misc",
  },
  "misc/icosahedron-6": {
    name: "Icosahedron 6",
    glb: "/GLB_Files/icosahedron6.glb",
    thumbnail: "/Models_PNG/Icosahedron6.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ffffff", "#ffffff", "#ffffff"],
    type: "Misc",
  },
  "misc/icosahedron-7": {
    name: "Icosahedron 7",
    glb: "/GLB_Files/icosahedron7.glb",
    thumbnail: "/Models_PNG/Icosahedron7.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ff7700"],
    cameraZ: 10,
    type: "Misc",
  },
  "misc/crystal-shape": {
    name: "Crystal Shape",
    glb: "/GLB_Files/crystalshape.glb",
    thumbnail: "/Models_PNG/CrystalShape.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 15,
    type: "Misc",
  },
  "misc/crystal-shape-2": {
    name: "Crystal Shape 2",
    glb: "/GLB_Files/crystalshape2.glb",
    thumbnail: "/Models_PNG/CrystalShape2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 15,
    type: "Misc",
  },
  "misc/boat-disk-1": {
    name: "Boat Disk 1",
    glb: "/GLB_Files/boatdisk1.glb",
    thumbnail: "/Models_PNG/BoatDisk1.png",
    palette: ["#00ff83"],
    cameraZ: 10,
    type: "Misc",
  },
  "misc/boat-disk-2": {
    name: "Boat Disk 2",
    glb: "/GLB_Files/boatdisk2.glb",
    thumbnail: "/Models_PNG/BoatDisk2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff", "#ff7700", "#ffe600", "#00e0ff", "#ff2266"],
    cameraZ: 10,
    type: "Misc",
  },
  "misc/hole-box": {
    name: "Hole Box",
    glb: "/GLB_Files/holebox.glb",
    thumbnail: "/Models_PNG/HoleBox.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    type: "Misc",
  },
  "misc/diagonal-box": {
    name: "Diagonal Box",
    glb: "/GLB_Files/diagonalbox.glb",
    thumbnail: "/Models_PNG/DiagonalBox.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    type: "Misc",
  },
  "misc/diagonal-box-2": {
    name: "Diagonal Box 2",
    glb: "/GLB_Files/diagonalbox2.glb",
    thumbnail: "/Models_PNG/DiagonalBox2.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    type: "Misc",
  },
  "misc/star-box": {
    name: "Star Box",
    glb: "/GLB_Files/starbox.glb",
    thumbnail: "/Models_PNG/StarBox.png",
    palette: ["#00ff83", "#0400ff", "#aa22ff"],
    cameraZ: 10,
    type: "Misc",
  },
};
